#!/bin/bash

##
# PCCS: Guerrilla Tactics dedicated server launcher and utilities.
#

#Not there on debian?
#source /etc/init.d/functions

PROJECTFOLDER="${HOME}/pccs/"
LOGFILE="${PROJECTFOLDER}dist/log.out"
BINFOLDER="${PROJECTFOLDER}dist/"
BIN="dedicated.run"
CENTRY="../sentry-guerrilla-tactics"

logo() {
    echo "   _____ _____ _____ _____   "
    echo "  |  _  |     |     |   __|  "
    echo "  |   __|  ===|  ===|__   |  "
    echo "  |__|  |_____|_____|_____|  "
    echo "                             "
}

loadpid() {
    pid=`ps -eo pid,comm | grep "sentry-guerr" | awk '{ print $1 }'`
}

stop() {
    loadpid
    if [ -n "$pid" ]; then
        echo "Killing sentry with PID #${pid}."
        kill -9 $pid
        #sleep 1
        echo "Killed."
    else
        echo "Sentry not running."
    fi

    PIDBIN=`ps -eo pid,comm | grep "dedicated.run" | awk '{ print $1 }'`
    if [ -n "${PIDBIN}" ]; then
        echo "Killing binary with PID #${PIDBIN}."
        kill -9 ${PIDBIN}
        echo "Killed."
    else
        echo "Binary not running."
    fi
}

start() {
    loadpid
    if [ -n "$pid" ]; then
        echo "Server already running."
    else
        echo "Starting sentry, which will spawn the server..."
        cd ${BINFOLDER}
        nohup ${CENTRY} ${BINFOLDER}${BIN} >> ${LOGFILE} 2>> ${LOGFILE} &
        #sleep 1
        loadpid
        echo "Sentry running with PID #${pid}.";
        PIDBIN=`ps -eo pid,comm | grep "dedicated.run" | awk '{ print $1 }'`
        echo "Binary running with PID #${PIDBIN}."
    fi
}

log() {
    loadpid
    if [ -n "$pid" ]; then
        tail -f ${LOGFILE}
    else
        echo "Logs are only available if the server is running."
    fi
}

pull() {
    echo "Pulling ${PROJECTFOLDER}";
    cd ${PROJECTFOLDER} && git pull

    echo "Pulling ${PROJECTFOLDER}phantom";
    cd ${PROJECTFOLDER}phantom && git pull

    echo "Pulling ${PROJECTFOLDER}libyaxl";
    cd ${PROJECTFOLDER}libyaxl && git pull
}

rebuild() {
    cd ${PROJECTFOLDER}dedicatedserver
    make clean
    make
}

build() {
    cd ${PROJECTFOLDER}dedicatedserver
    make
}

run() {
    loadpid
    if [ -n "$pid" ]; then
        echo "Server already running. Kill it first via pccs stop."
    else
        cd ${BINFOLDER}
        ${CENTRY} ./${BIN}
    fi
}

logo

if [ "${EUID}" -eq 0 ]; then
    echo "It's unsafe to run this as root. You should know better. Aborting."
    exit 1
fi

for OPTION in "$@"
do
    case "${OPTION}" in
        start)
            start
            ;;
        stop)
            stop
            ;;
        status)
            loadpid
            echo "The centry PID, if any: #${pid}."
            PIDBIN=`ps -eo pid,comm | grep "dedicated.run" | awk '{ print $1 }'`
            echo "The binary PID, if any: #${PIDBIN}."
            ;;
        log)
            log
            ;;
        restart)
            stop
            start
            ;;
        rebuild)
            rebuild
            ;;
        run)
            run
            ;;
        build)
            build
            ;;
        pull)
            pull
            ;;
        all)
            pull
            build
            stop
            run
            ;;
        *)
            echo $"Usage: $0 {start|stop|restart|status|log|pull|run|rebuild|build|all}. Any combination of options is available."
    esac
    echo "---"
    echo ""
done

exit 1
